# Generated by Django 5.0.3 on 2024-04-11 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massage',
            old_name='stuff',
            new_name='item',
        ),
    ]
