# Generated by Django 5.0.3 on 2024-04-11 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_city_country_alter_city_state_and_more'),
        ('messaging', '0002_rename_stuff_massage_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.item'),
        ),
    ]
