# Generated by Django 5.0.4 on 2024-04-11 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_item_category'),
        ('messaging', '0003_alter_massage_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateField()),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Massage',
        ),
    ]
