# Generated by Django 5.0.3 on 2024-04-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_state_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_parent',
        ),
    ]
