# Generated by Django 5.0.3 on 2024-04-11 03:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_category_cat_parent'),
        ('messaging', '0002_rename_stuff_massage_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stuff',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='stuff',
            new_name='item',
        ),
    ]
