# Generated by Django 5.0.4 on 2024-04-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_city_country_alter_city_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='media_path',
        ),
        migrations.AddField(
            model_name='media',
            name='media_item',
            field=models.ImageField(blank=True, upload_to='./static/media/'),
        ),
    ]
