# Generated by Django 5.0.4 on 2024-04-11 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_media_media_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_item', models.ImageField(blank=True, upload_to='catalog/static/media/%Y/%m/%d/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
