# Generated by Django 5.0.4 on 2024-04-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_image_delete_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='media_item',
            new_name='image',
        ),
    ]
