# Generated by Django 5.0.4 on 2024-04-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/%Y/%m/%d/', verbose_name='Path to image'),
        ),
    ]
