# Generated by Django 5.0.4 on 2024-04-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_item_location_alter_location_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_path',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='catalog/categories/', verbose_name='Path to image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='catalog/img/%Y%m%d/', verbose_name='Path to image'),
        ),
    ]
